server:
  port: 8090

spring:
  application:
    name: Baas_chargeslip-pdf-service
  profiles:
    active: local

logging:
  level:
    root: INFO
    com.pinelabs.chargeslip: DEBUG

http:
  client:
    connect-timeout: 3000
    read-timeout: 8000
